import React, { useState } from 'react';
import { Presentation, Loader2, Download, CheckCircle, FileText, MonitorPlay, Palette, Briefcase } from 'lucide-react';
import { generateSlideContent } from '../services/geminiService';
import PptxGenJS from 'pptxgenjs';
import { PresentationStructure } from '../types';

export const PPTBuilder: React.FC = () => {
  const [topic, setTopic] = useState('');
  const [slideCount, setSlideCount] = useState(5);
  const [isGenerating, setIsGenerating] = useState(false);
  const [presentationData, setPresentationData] = useState<PresentationStructure | null>(null);
  const [error, setError] = useState<string | null>(null);

  const handleGenerate = async () => {
    if (!topic.trim()) return;
    setIsGenerating(true);
    setError(null);
    setPresentationData(null);

    try {
      const data = await generateSlideContent(topic, slideCount);
      setPresentationData(data);
    } catch (err) {
      console.error(err);
      setError("Failed to generate presentation content. Please try again.");
    } finally {
      setIsGenerating(false);
    }
  };

  const downloadPPT = () => {
    if (!presentationData) return;

    const pptx = new PptxGenJS();
    const { slides, themeColor, sentiment } = presentationData;
    
    // McKinsey Style Layout Definition
    // A Layout usually has a dedicated header area and a footer.
    pptx.layout = 'LAYOUT_16x9';

    // Define Master Slide for Professional Look
    pptx.defineSlideMaster({
      title: 'MASTER_SLIDE',
      background: { color: 'FFFFFF' }, // Clean white background
      objects: [
        // Top Bar Line (Subtle)
        { rect: { x: 0.5, y: 1.2, w: '90%', h: 0.05, fill: { color: themeColor } } },
        // Footer Line
        { rect: { x: 0.5, y: 7.0, w: '90%', h: 0.02, fill: { color: 'D3D3D3' } } },
        // Footer Text
        { text: { text: 'CONFIDENTIAL', options: { x: 0.5, y: 7.1, fontSize: 8, color: '888888' } } },
        { text: { text: `Generated by OmniGem | Topic: ${topic}`, options: { x: 3, y: 7.1, w: 4, align: 'center', fontSize: 8, color: '888888' } } },
      ],
      slideNumber: { x: 9.0, y: 7.1, fontSize: 8, color: '888888' }
    });

    // 1. Title Slide (Impactful, Solid Color)
    const titleSlide = pptx.addSlide();
    titleSlide.background = { color: themeColor };
    titleSlide.addText(topic, { 
      x: 1, y: 2.5, w: 8, h: 1.5, 
      fontSize: 32, color: 'FFFFFF', align: 'left', fontFace: 'Arial', bold: true 
    });
    titleSlide.addText(`Consultation Report\n${new Date().toLocaleDateString()}`, { 
      x: 1, y: 4.2, w: 8, h: 1, 
      fontSize: 14, color: 'EEEEEE', align: 'left', fontFace: 'Arial' 
    });

    // 2. Content Slides
    slides.forEach((slide) => {
      const s = pptx.addSlide({ masterName: 'MASTER_SLIDE' });
      
      // Action Title (Top left, Sentence case, Professional)
      s.addText(slide.title, { 
        x: 0.5, y: 0.4, w: 9, h: 0.8, 
        fontSize: 20, color: themeColor, bold: true, fontFace: 'Arial', valign: 'top' 
      });
      
      // Content Bullets (Clean, spaced)
      if (slide.content && slide.content.length > 0) {
        s.addText(slide.content.map(c => ({ text: c, options: { breakLine: true } })), { 
          x: 0.5, 
          y: 1.5, 
          w: 9, 
          h: 4.8, 
          fontSize: 14, 
          color: '333333', 
          fontFace: 'Arial',
          bullet: { type: 'number' },
          lineSpacing: 28, // Open spacing for readability
          valign: 'top'
        });
      }

      // Speaker Notes
      if (slide.speakerNotes) {
        s.addNotes(slide.speakerNotes);
      }
    });

    pptx.writeFile({ fileName: `OmniGem-${topic.replace(/\s+/g, '-')}.pptx` });
  };

  return (
    <div className="flex flex-col h-full w-full max-w-5xl mx-auto overflow-y-auto">
      <div className="p-8">
        <h2 className="text-3xl font-bold mb-6 flex items-center gap-3 text-white">
            <Presentation className="text-[#FF4B4B]" size={32} />
            Presentation Builder
            <span className="text-xs font-normal text-gray-400 bg-[#3b3d45] px-2 py-1 rounded ml-2">McKinsey Style</span>
        </h2>

        {/* Input Section */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
            <div className="md:col-span-2 space-y-4">
                <div className="bg-[#262730] p-6 rounded-md border border-[#3b3d45]">
                    <label className="block text-sm font-semibold text-white mb-2">Consultation Topic</label>
                    <input 
                        type="text" 
                        value={topic}
                        onChange={(e) => setTopic(e.target.value)}
                        placeholder="e.g., Market Entry Strategy for EV Charging in SE Asia"
                        className="w-full bg-[#0E1117] border border-[#4B4B4B] rounded-md px-4 py-3 text-white focus:border-[#FF4B4B] outline-none placeholder-gray-600"
                    />
                    
                    <div className="mt-4">
                         <label className="block text-sm font-semibold text-white mb-2">Number of Slides</label>
                         <input 
                            type="range" 
                            min="3" 
                            max="15" 
                            value={slideCount} 
                            onChange={(e) => setSlideCount(parseInt(e.target.value))}
                            className="w-full accent-[#FF4B4B]"
                         />
                         <div className="text-right text-xs text-gray-400 mt-1">{slideCount} Slides</div>
                    </div>

                    <button
                        onClick={handleGenerate}
                        disabled={isGenerating || !topic.trim()}
                        className="mt-6 w-full py-3 bg-[#FF4B4B] hover:bg-[#FF3333] disabled:opacity-50 text-white rounded-md font-semibold transition-colors flex items-center justify-center gap-2"
                    >
                        {isGenerating ? <Loader2 className="animate-spin" size={18} /> : <MonitorPlay size={18} />}
                        Generate Analysis
                    </button>
                    {error && <p className="text-red-400 text-xs mt-3">{error}</p>}
                </div>
            </div>

            {/* Status / Instructions */}
            <div className="bg-[#262730] p-6 rounded-md border border-[#3b3d45] h-fit">
                 <h3 className="font-semibold mb-3 text-sm flex items-center gap-2">
                    <Briefcase size={16} className="text-[#FF4B4B]" />
                    Consulting Standard
                 </h3>
                 <ul className="space-y-3 text-sm text-gray-400">
                    <li className="flex gap-2 items-start">
                        <span className="text-[#FF4B4B] font-bold">•</span>
                        <span>Uses <strong>Action Titles</strong> that synthesize insights, not just describe topics.</span>
                    </li>
                    <li className="flex gap-2 items-start">
                        <span className="text-[#FF4B4B] font-bold">•</span>
                        <span>Applies <strong>MECE</strong> principles to bullet points.</span>
                    </li>
                    <li className="flex gap-2 items-start">
                        <span className="text-[#FF4B4B] font-bold">•</span>
                        <span>Auto-selects <strong>Corporate Themes</strong> based on sentiment analysis.</span>
                    </li>
                 </ul>
            </div>
        </div>

        {/* Results Section */}
        {presentationData && (
            <div className="animate-fade-in border-t border-[#3b3d45] pt-6">
                <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-6 gap-4">
                    <div>
                        <h3 className="text-xl font-bold text-white mb-1">Executive Summary</h3>
                        <div className="flex items-center gap-3">
                            <span className={`px-2 py-0.5 rounded text-[10px] uppercase font-bold tracking-wider ${
                                presentationData.sentiment === 'positive' ? 'bg-green-900 text-green-300' :
                                presentationData.sentiment === 'negative' ? 'bg-red-900 text-red-300' :
                                presentationData.sentiment === 'urgent' ? 'bg-orange-900 text-orange-300' :
                                'bg-blue-900 text-blue-300'
                            }`}>
                                {presentationData.sentiment} Sentiment
                            </span>
                            <div className="flex items-center gap-1 text-xs text-gray-400">
                                <Palette size={12} />
                                Theme: <span className="inline-block w-3 h-3 rounded-full" style={{ backgroundColor: presentationData.themeColor }}></span>
                                <span className="font-mono">{presentationData.themeColor}</span>
                            </div>
                        </div>
                    </div>
                    <button 
                        onClick={downloadPPT}
                        className="flex items-center gap-2 px-6 py-2 bg-white text-black hover:bg-gray-200 rounded-md text-sm font-bold transition-colors"
                    >
                        <Download size={16} /> Download .pptx
                    </button>
                </div>
                
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                    {presentationData.slides.map((slide, idx) => (
                        <div key={idx} className="bg-white p-4 rounded-sm border-t-4 h-full flex flex-col group" style={{ borderColor: presentationData.themeColor }}>
                            <div className="flex justify-between items-start mb-3 border-b border-gray-100 pb-2">
                                <span className="text-[10px] font-bold text-gray-400 uppercase tracking-widest">Slide {idx + 1}</span>
                                <FileText size={12} className="text-gray-300" />
                            </div>
                            <h4 className="font-bold text-sm mb-3 leading-snug text-gray-900 font-sans">{slide.title}</h4>
                            <ul className="space-y-2 mb-4 flex-1">
                                {slide.content.slice(0, 5).map((bullet, bIdx) => (
                                    <li key={bIdx} className="text-xs text-gray-600 flex gap-2 leading-relaxed">
                                        <span style={{ color: presentationData.themeColor }}>•</span>
                                        {bullet}
                                    </li>
                                ))}
                            </ul>
                            {slide.speakerNotes && (
                                <div className="pt-2 border-t border-gray-100 mt-auto">
                                    <p className="text-[9px] text-gray-400 line-clamp-2 italic">"{slide.speakerNotes}"</p>
                                </div>
                            )}
                        </div>
                    ))}
                </div>
            </div>
        )}
      </div>
    </div>
  );
};